// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "my-first-sls-project",
    "version": "1"
  },
  "paths": {
    "/{id}": {
      "get": {
        "summary": "api",
        "description": "",
        "operationId": "api.get./{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "limit",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};