// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "my-first-sls-project",
    "version": "1"
  },
  "paths": {
    "/{id}": {
      "get": {
        "summary": "api",
        "description": "",
        "operationId": "api.get./{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Home"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "limit",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/register": {
      "post": {
        "summary": "register",
        "description": "",
        "operationId": "register.post./register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Register"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Home": {
      "properties": {
        "id": {
          "title": "Home.id",
          "type": "number"
        },
        "name": {
          "title": "Home.name",
          "type": "string"
        },
        "description": {
          "title": "Home.description",
          "type": "string"
        },
        "price": {
          "title": "Home.price",
          "type": "number"
        },
        "image": {
          "title": "Home.image",
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "price",
        "image"
      ],
      "additionalProperties": false,
      "title": "Home",
      "type": "object"
    },
    "Register": {
      "properties": {
        "username": {
          "title": "Register.username",
          "type": "string"
        },
        "password": {
          "title": "Register.password",
          "type": "string"
        }
      },
      "required": [
        "username",
        "password"
      ],
      "additionalProperties": false,
      "title": "Register",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};